server {
    listen 80;
    
    # Корневая папка, где лежат наши файлы
    root /usr/share/nginx/html;
    index index.html;

    # Сжатие файлов, чтобы сайт грузился быстрее
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Самая важная строка для React Router:
        # Пытаемся найти файл -> если нет, ищем папку -> если нет, отдаем index.html
        try_files $uri $uri/ /index.html;
    }
}